# LOGISTIC REGRESSION

### Iris flower Classification

In [1]:
## importing all the necessary libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math
import random

## Binary Classification

In [2]:
def sigmoid(X):
    
    Y = 1 / (1 + np.exp(-X))
    
    return Y    

In [3]:
x_temp = np.random.rand(5,6)
y_temp = sigmoid(x_temp)
print(x_temp)
print(y_temp)

[[0.77838949 0.71341529 0.22864337 0.7163827  0.14585601 0.94898552]
 [0.07797518 0.43410064 0.45190145 0.47596663 0.92414686 0.50890871]
 [0.88632973 0.33822883 0.57178107 0.51884112 0.71297779 0.12450974]
 [0.74145629 0.20270308 0.01236018 0.5101934  0.94298345 0.37746322]
 [0.78488962 0.29830764 0.05340111 0.49001354 0.79305153 0.31170127]]
[[0.68533291 0.67115537 0.55691312 0.67180997 0.5363995  0.72091111]
 [0.51948392 0.60685244 0.61109123 0.616795   0.7158863  0.62455062]
 [0.70813218 0.58376022 0.63917405 0.62687674 0.67105881 0.53108728]
 [0.67731422 0.55050296 0.50309001 0.62485181 0.71970191 0.59326112]
 [0.68673298 0.57402875 0.51334711 0.62010962 0.68848618 0.57730047]]


## Cost function

In [4]:
def cost_fun(y,h):
    
    cost = -1/y.size * np.sum( np.dot(y.T,np.log(h)) + np.dot(1-y.T, np.log(1-h)))
    
    return cost

In [5]:
def gradient(X):
    
    X = sigmoid(X)*(1-sigmoid(X))
    
    return X    

In [6]:
x_temp = np.random.rand(5,6)

y_temp = [1.,0.,1.,1.,0.]
y_temp = np.array(y_temp)
y_temp = np.expand_dims(y_temp,axis = 1)

w_temp = np.random.rand(x_temp.shape[1],1)

y_hat = sigmoid(np.dot(x_temp,w_temp))

cost = cost_fun(y_temp,y_hat)
print("cost : {}".format(cost))

g = gradient(np.dot(x_temp,w_temp))
print(f"gradient : {g}")

cost : 0.7511473776874835
gradient : [[0.14680127]
 [0.16778097]
 [0.18120043]
 [0.15267399]
 [0.16917467]]


## loading a datasets of iris flower classification

In [7]:
iris_data = pd.read_csv(r"IRIS.csv")
iris_data.head(10)

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
5           5.4          3.9           1.7          0.4  Iris-setosa
6           4.6          3.4           1.4          0.3  Iris-setosa
7           5.0          3.4           1.5          0.2  Iris-setosa
8           4.4          2.9           1.4          0.2  Iris-setosa
9           4.9          3.1           1.5          0.1  Iris-setosa

### storeing the data set in a array from tabular form

In [8]:
iris_data = np.array(iris_data)
print(iris_data.shape)
print(iris_data)

(150, 5)
[[5.1 3.5 1.4 0.2 'Iris-setosa']
 [4.9 3.0 1.4 0.2 'Iris-setosa']
 [4.7 3.2 1.3 0.2 'Iris-setosa']
 [4.6 3.1 1.5 0.2 'Iris-setosa']
 [5.0 3.6 1.4 0.2 'Iris-setosa']
 [5.4 3.9 1.7 0.4 'Iris-setosa']
 [4.6 3.4 1.4 0.3 'Iris-setosa']
 [5.0 3.4 1.5 0.2 'Iris-setosa']
 [4.4 2.9 1.4 0.2 'Iris-setosa']
 [4.9 3.1 1.5 0.1 'Iris-setosa']
 [5.4 3.7 1.5 0.2 'Iris-setosa']
 [4.8 3.4 1.6 0.2 'Iris-setosa']
 [4.8 3.0 1.4 0.1 'Iris-setosa']
 [4.3 3.0 1.1 0.1 'Iris-setosa']
 [5.8 4.0 1.2 0.2 'Iris-setosa']
 [5.7 4.4 1.5 0.4 'Iris-setosa']
 [5.4 3.9 1.3 0.4 'Iris-setosa']
 [5.1 3.5 1.4 0.3 'Iris-setosa']
 [5.7 3.8 1.7 0.3 'Iris-setosa']
 [5.1 3.8 1.5 0.3 'Iris-setosa']
 [5.4 3.4 1.7 0.2 'Iris-setosa']
 [5.1 3.7 1.5 0.4 'Iris-setosa']
 [4.6 3.6 1.0 0.2 'Iris-setosa']
 [5.1 3.3 1.7 0.5 'Iris-setosa']
 [4.8 3.4 1.9 0.2 'Iris-setosa']
 [5.0 3.0 1.6 0.2 'Iris-setosa']
 [5.0 3.4 1.6 0.4 'Iris-setosa']
 [5.2 3.5 1.5 0.2 'Iris-setosa']
 [5.2 3.4 1.4 0.2 'Iris-setosa']
 [4.7 3.2 1.6 0.2 'Iris-setosa']
 

**y stores the data values of 4th column and x stores the other 4 parameters.**

In [9]:
y = iris_data[:,4]
print(len(y))
print(y)

150
['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versic

In [10]:
x=np.array(iris_data[:,:4],dtype=float) # Or x=np.array(iris_data[:,0:4],dtype=float)
print(len(x))
print(x)

150
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.

### Feature Scaling

In [11]:
temp_mean= np.mean(x,axis=0)      #the mean value of x
x = x-temp_mean

print(x) 

[[-7.43333333e-01  4.46000000e-01 -2.35866667e+00 -9.98666667e-01]
 [-9.43333333e-01 -5.40000000e-02 -2.35866667e+00 -9.98666667e-01]
 [-1.14333333e+00  1.46000000e-01 -2.45866667e+00 -9.98666667e-01]
 [-1.24333333e+00  4.60000000e-02 -2.25866667e+00 -9.98666667e-01]
 [-8.43333333e-01  5.46000000e-01 -2.35866667e+00 -9.98666667e-01]
 [-4.43333333e-01  8.46000000e-01 -2.05866667e+00 -7.98666667e-01]
 [-1.24333333e+00  3.46000000e-01 -2.35866667e+00 -8.98666667e-01]
 [-8.43333333e-01  3.46000000e-01 -2.25866667e+00 -9.98666667e-01]
 [-1.44333333e+00 -1.54000000e-01 -2.35866667e+00 -9.98666667e-01]
 [-9.43333333e-01  4.60000000e-02 -2.25866667e+00 -1.09866667e+00]
 [-4.43333333e-01  6.46000000e-01 -2.25866667e+00 -9.98666667e-01]
 [-1.04333333e+00  3.46000000e-01 -2.15866667e+00 -9.98666667e-01]
 [-1.04333333e+00 -5.40000000e-02 -2.35866667e+00 -1.09866667e+00]
 [-1.54333333e+00 -5.40000000e-02 -2.65866667e+00 -1.09866667e+00]
 [-4.33333333e-02  9.46000000e-01 -2.55866667e+00 -9.98666667e

### Spliting the datasets into 80% train set and 20% test set

In [12]:
train = random.sample(range(0,150),120)
print(len(train))
print(train)

120
[47, 146, 102, 92, 55, 50, 24, 21, 126, 137, 19, 135, 65, 23, 16, 25, 12, 125, 30, 117, 94, 34, 3, 69, 85, 97, 10, 108, 83, 80, 74, 106, 78, 26, 46, 13, 116, 57, 91, 56, 88, 52, 48, 53, 99, 43, 17, 5, 63, 140, 86, 29, 58, 123, 27, 2, 104, 145, 14, 115, 35, 101, 112, 20, 70, 103, 119, 131, 61, 73, 143, 132, 130, 7, 64, 6, 111, 8, 38, 37, 122, 22, 105, 31, 75, 90, 18, 129, 66, 133, 139, 121, 82, 36, 100, 87, 59, 142, 44, 4, 136, 113, 40, 138, 42, 93, 67, 110, 98, 28, 1, 39, 84, 0, 49, 11, 41, 9, 68, 147]


In [13]:
validation = [i for i in range (150) if not (i in train)]
print(len(validation))
print(validation)

30
[15, 32, 33, 45, 51, 54, 60, 62, 71, 72, 76, 77, 79, 81, 89, 95, 96, 107, 109, 114, 118, 120, 124, 127, 128, 134, 141, 144, 148, 149]


#### Here x_train is our input training data and y_train is our output training data

In [14]:
x_train=(x[train,:4])
print(x_train.shape)
print (x_train)

(120, 4)
[[-1.24333333e+00  1.46000000e-01 -2.35866667e+00 -9.98666667e-01]
 [ 4.56666667e-01 -5.54000000e-01  1.24133333e+00  7.01333333e-01]
 [ 1.25666667e+00 -5.40000000e-02  2.14133333e+00  9.01333333e-01]
 [-4.33333333e-02 -4.54000000e-01  2.41333333e-01  1.33333333e-03]
 [-1.43333333e-01 -2.54000000e-01  7.41333333e-01  1.01333333e-01]
 [ 1.15666667e+00  1.46000000e-01  9.41333333e-01  2.01333333e-01]
 [-1.04333333e+00  3.46000000e-01 -1.85866667e+00 -9.98666667e-01]
 [-7.43333333e-01  6.46000000e-01 -2.25866667e+00 -7.98666667e-01]
 [ 3.56666667e-01 -2.54000000e-01  1.04133333e+00  6.01333333e-01]
 [ 5.56666667e-01  4.60000000e-02  1.74133333e+00  6.01333333e-01]
 [-7.43333333e-01  7.46000000e-01 -2.25866667e+00 -8.98666667e-01]
 [ 1.85666667e+00 -5.40000000e-02  2.34133333e+00  1.10133333e+00]
 [ 8.56666667e-01  4.60000000e-02  6.41333333e-01  2.01333333e-01]
 [-7.43333333e-01  2.46000000e-01 -2.05866667e+00 -6.98666667e-01]
 [-4.43333333e-01  8.46000000e-01 -2.45866667e+00 -7.

### Now we added a column of 1 in the x_train array 

In [15]:
x_train = np.concatenate((x_train,np.ones((120,1),dtype=float)),axis=1)
print(x_train.shape)

(120, 5)


### Now we defined a array y_train of 120*3 whose each every element is 0 and it will define the output 
### If one data is of first class of 3 then it will make the first element of that row 1 , similarly for 2nd class second element of the row becomes 1 and for last class 3rd element of the row of y_train will become 1.

In [16]:
y_train = np.zeros((120,3)) 
print(y_train)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0.

In [17]:
for i,j in zip(train,range(120)):
    if y[i]=='Iris-setosa':
        y_train[j,0]=1                 # for iris_data in setosa make 1 in y_train
    if y[i]=='Iris-versicolor':
        y_train[j,1]=1                 # for iris_data in versicolor make 1 in y_train
    if y[i]=='Iris-virginica':
        y_train[j,2]=1                 # for iris_data in virginica make 1 in y_train
print(y_train)

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1.

### Similarly we will proceed for the validation dataset

In [18]:
x_test =(x[validation,:4])
x_test = np.concatenate((x_test,np.ones((30,1))),axis=1)
print(x_test)

[[-1.43333333e-01  1.34600000e+00 -2.25866667e+00 -7.98666667e-01
   1.00000000e+00]
 [-6.43333333e-01  1.04600000e+00 -2.25866667e+00 -1.09866667e+00
   1.00000000e+00]
 [-3.43333333e-01  1.14600000e+00 -2.35866667e+00 -9.98666667e-01
   1.00000000e+00]
 [-1.04333333e+00 -5.40000000e-02 -2.35866667e+00 -8.98666667e-01
   1.00000000e+00]
 [ 5.56666667e-01  1.46000000e-01  7.41333333e-01  3.01333333e-01
   1.00000000e+00]
 [ 6.56666667e-01 -2.54000000e-01  8.41333333e-01  3.01333333e-01
   1.00000000e+00]
 [-8.43333333e-01 -1.05400000e+00 -2.58666667e-01 -1.98666667e-01
   1.00000000e+00]
 [ 1.56666667e-01 -8.54000000e-01  2.41333333e-01 -1.98666667e-01
   1.00000000e+00]
 [ 2.56666667e-01 -2.54000000e-01  2.41333333e-01  1.01333333e-01
   1.00000000e+00]
 [ 4.56666667e-01 -5.54000000e-01  1.14133333e+00  3.01333333e-01
   1.00000000e+00]
 [ 9.56666667e-01 -2.54000000e-01  1.04133333e+00  2.01333333e-01
   1.00000000e+00]
 [ 8.56666667e-01 -5.40000000e-02  1.24133333e+00  5.01333333e-01

In [19]:
y_test = np.zeros((30,3))
print(y_test)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Simialrly we change the y_test array as per given data in the dataset

In [20]:
for i,j in zip(validation,range(120)):
    if y[i]=='Iris-setosa':
        y_test[j,0]=1             # for iris_data in setosa make 1 in y_train
    if y[i]=='Iris-versicolor':
        y_test[j,1]=1             # for iris_data in vericolor make 1 in y_train
    if y[i]=='Iris-virginica':
        y_test[j,2]=1             # for iris_data in virginica make 1 in y_train
print(y_test)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]


## Gradient descent 
### Now we will define theta a 5*3 matrix which will give gradient for each parameter  for each class

Weight matrix for logistice regression will have shape = (no_of_features + 1, no_of_classes)

In [21]:
def initialize_parameters(x,classes):
    
    n = x.shape[1]
    theta = np.random.rand(n, classes)*0.01
    
    return theta

In [22]:
def predict_prob(x, theta):
    
    h = sigmoid(np.dot(x,theta))
    
    return h

In [23]:
def accuracy(h, y):
    
    m = y.shape[0]
    h = np.argmax(h,axis=1)                          # max value in each row of h array of sigmoid function
    q = np.argmax(y,axis=1) == h                     # check how many output we got correct
    print(np.sum(q*100/m))
    

## Model

In [24]:
def model(x, y, classes = 3, learning_rate = 1, iterations = 1000):
    
    m = x.shape[0]
    theta = initialize_parameters(x, classes)
    
    for i in range (iterations):
        h = predict_prob(x, theta)                          # sigmoid function update
        theta -= ((learning_rate)/m)*(np.dot((h-y).T , x).T)    # theta update
    
    accuracy(h,y)
    
    return theta

In [25]:
theta = model(x_train, y_train, learning_rate = 3, iterations = 5000)
theta

97.50000000000001


array([[  0.90613889,  -0.83931796,  -0.94670815],
       [  4.39355545,  -2.17669855,  -5.45927841],
       [ -5.74106682,   1.97669799,   6.7233214 ],
       [ -3.05135905,  -3.40802088,  13.60186179],
       [ -6.31860481,  -1.10270412, -14.58195353]])

### Now we will test our test data set and see the accuracy 

In [26]:
h = predict_prob(x_test, theta)
accuracy(h, y_test)

96.66666666666664
